from enum import StrEnum


class ReviewDecision(StrEnum):
    PUBLISH = "PUBLISH"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    REJECT = "REJECT"
    TRANSFER = "TRANSFER"


class ReviewAction(StrEnum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    KEEP_CURRENT = "KEEP_CURRENT"
    ARCHIVE = "ARCHIVE"
    MARK_DUPLICATE = "MARK_DUPLICATE"
    SPLIT_BY_SCOPE = "SPLIT_BY_SCOPE"
    MARK_INSUFFICIENT = "MARK_INSUFFICIENT"


class ProblemTag(StrEnum):
    DUPLICATE = "DUPLICATE"
    OVERLAP = "OVERLAP"
    CONFLICT = "CONFLICT"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    PARSE_ERROR = "PARSE_ERROR"
    OUTDATED = "OUTDATED"
    MISSING_SCOPE = "MISSING_SCOPE"
    CONTENT_MISSING = "CONTENT_MISSING"


class CrossDocumentRelationType(StrEnum):
    EXACT_DUPLICATE = "EXACT_DUPLICATE"
    OVERLAP = "OVERLAP"
    COMPLEMENTARY = "COMPLEMENTARY"
    CONDITIONAL_VARIANT = "CONDITIONAL_VARIANT"
    CONFLICT = "CONFLICT"
    INSUFFICIENT = "INSUFFICIENT"


class KnowledgeSourceRole(StrEnum):
    PRIMARY = "PRIMARY"
    ALIAS = "ALIAS"
    SUPPORTING = "SUPPORTING"
