from enum import StrEnum


class ReviewDecision(StrEnum):
    PUBLISH = "PUBLISH"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    REJECT = "REJECT"
    TRANSFER = "TRANSFER"


class ReviewAction(StrEnum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    KEEP_CURRENT = "KEEP_CURRENT"
    ARCHIVE = "ARCHIVE"
    MARK_DUPLICATE = "MARK_DUPLICATE"
    SPLIT_BY_SCOPE = "SPLIT_BY_SCOPE"
    MARK_INSUFFICIENT = "MARK_INSUFFICIENT"


class ReviewType(StrEnum):
    NEW = "NEW"
    UPDATE = "UPDATE"
    CONFLICT = "CONFLICT"
    STALE = "STALE"


class ReviewTriggerType(StrEnum):
    SOURCE_VERSION = "SOURCE_VERSION"
    LIFECYCLE = "LIFECYCLE"
    FEEDBACK = "FEEDBACK"


class ReviewSubjectType(StrEnum):
    MATERIAL_VERSION = "MATERIAL_VERSION"
    KNOWLEDGE_UNIT = "KNOWLEDGE_UNIT"
    COMPARISON_RELATION = "COMPARISON_RELATION"
    KNOWLEDGE = "KNOWLEDGE"


class ReviewPackageStatus(StrEnum):
    OPEN = "OPEN"
    WAITING_SOURCE_CHANGE = "WAITING_SOURCE_CHANGE"
    WAITING_BUSINESS_CONFIRMATION = "WAITING_BUSINESS_CONFIRMATION"
    COMPLETED = "COMPLETED"
    INVALIDATED = "INVALIDATED"


class ReviewItemStatus(StrEnum):
    PENDING = "PENDING"
    WAITING_SOURCE_CHANGE = "WAITING_SOURCE_CHANGE"
    WAITING_BUSINESS_CONFIRMATION = "WAITING_BUSINESS_CONFIRMATION"
    DECIDED = "DECIDED"
    SOURCE_UPDATED = "SOURCE_UPDATED"
    INVALIDATED = "INVALIDATED"


class ReviewOutcome(StrEnum):
    PUBLISH = "PUBLISH"
    REQUEST_SOURCE_CHANGE = "REQUEST_SOURCE_CHANGE"
    EXCLUDE = "EXCLUDE"
    ADOPT_NEW_VERSION = "ADOPT_NEW_VERSION"
    KEEP_CURRENT = "KEEP_CURRENT"
    SPLIT_SCOPE = "SPLIT_SCOPE"
    WAIT_BUSINESS_CONFIRMATION = "WAIT_BUSINESS_CONFIRMATION"
    CONFIRM_VALID = "CONFIRM_VALID"
    REQUEST_SUPPORTING_SOURCE = "REQUEST_SUPPORTING_SOURCE"
    ARCHIVE = "ARCHIVE"
    DISMISS = "DISMISS"
    DUPLICATE_SOURCE = "DUPLICATE_SOURCE"


class SourceChangeRequestStatus(StrEnum):
    OPEN = "OPEN"
    NEW_VERSION_RECEIVED = "NEW_VERSION_RECEIVED"
    FULFILLED = "FULFILLED"
    CANCELLED = "CANCELLED"


class ProblemTag(StrEnum):
    DUPLICATE = "DUPLICATE"
    OVERLAP = "OVERLAP"
    CONFLICT = "CONFLICT"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    PARSE_ERROR = "PARSE_ERROR"
    OUTDATED = "OUTDATED"
    MISSING_SCOPE = "MISSING_SCOPE"
    CONTENT_MISSING = "CONTENT_MISSING"


class CrossDocumentRelationType(StrEnum):
    EXACT_DUPLICATE = "EXACT_DUPLICATE"
    OVERLAP = "OVERLAP"
    COMPLEMENTARY = "COMPLEMENTARY"
    CONDITIONAL_VARIANT = "CONDITIONAL_VARIANT"
    CONFLICT = "CONFLICT"
    INSUFFICIENT = "INSUFFICIENT"


class KnowledgeSourceRole(StrEnum):
    PRIMARY = "PRIMARY"
    ALIAS = "ALIAS"
    SUPPORTING = "SUPPORTING"


class DuplicateResolutionStrategy(StrEnum):
    USE_SOURCE = "USE_SOURCE"
    USE_TARGET = "USE_TARGET"
    KEEP_SEPARATE = "KEEP_SEPARATE"
